#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"

######################## default configuration ####################
baseURL = "https://febricity.app"
title = "Febricity"
theme = "persian"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "5"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

############################# output ##############################
[outputs]
home = [ "HTML", "RSS", "json"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


################################ menu ##################################
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Features"
url = "features"
weight = 2

[[menu.main]]
name = "Demos"
url = "demos"
weight = 3

[[menu.main]]
name = "Requirements"
url = "requirements"
weight = 3

[[menu.main]]
name = "Download"
url = "download"
weight = 4


#################### default parameters ################################
[params]
logo = "images/feblogofinalcropped.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# search
search = true
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright
#copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# cookies
[params.cookies]
enable = true
expire_days = 2
